version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
    container_name: quiz-application
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres