spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/quizdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

quiz:
  correct-answer:
    points: 1

server:
  port: 9090